<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="40" started-at="2016-01-22T18:42:05Z" finished-at="2016-01-22T18:42:05Z">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="40" started-at="2016-01-22T18:42:05Z" finished-at="2016-01-22T18:42:05Z">
      <class name="se.nrm.dina.data.exceptions.DinaExceptionNGTest">
        <test-method status="PASS" signature="testGetErrorCode()[pri:0, instance:se.nrm.dina.data.exceptions.DinaExceptionNGTest@1e643faf]" name="testGetErrorCode" duration-ms="21" started-at="2016-01-22T19:42:05Z" finished-at="2016-01-22T19:42:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetErrorCode -->
      </class> <!-- se.nrm.dina.data.exceptions.DinaExceptionNGTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
